#!/usr/bin/env bash
# Package the exploration editor as a standalone Windows 64-bit build.
#
#   bash _mod_tools/package_editor_win.sh
#
# Produces _mod_tools/dist/CellToSingularityEditor-win64.zip containing:
#   CePackEditor.exe   the fused app (love.exe + the .love archive), double-click to run
#   love.exe           fallback launcher; drag editor.love onto it if the fused build misbehaves
#   editor.love        the same archive, unfused
#   7 runtime dlls     must stay next to the exe
#   使用说明.txt        usage notes
#
# The build is a RELEASE build: src/build.lua is written with release = true, which disables the
# self test and the smoke test and keeps src/selftest.lua out of the archive entirely.
set -euo pipefail

DATA="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ED="$DATA/_mod_tools/CustomEventPackEditor"
LW="/home/forin/lovewin/love-11.5-win64"
DIST="$DATA/_mod_tools/dist"
OUT="$DIST/Editor-win64"
STAGE="$OUT/stage"

[ -f "$LW/love.exe" ] || { echo "missing Windows LÖVE at $LW"; exit 1; }

rm -rf "$OUT"
mkdir -p "$STAGE"

# ---- 1. source files that belong in the shipped archive -------------------------------
# note: smoketest_*.png screenshots and editor.cfg are development artifacts and stay out
cp "$ED/conf.lua" "$ED/main.lua" "$ED/README.md" "$STAGE/"
cp -r "$ED/src" "$STAGE/src"
rm -f "$STAGE/src/selftest.lua"          # the self test is not part of a release

# ---- 2. release marker: this is what turns the test entry points off -------------------
cat > "$STAGE/src/build.lua" <<'LUA'
-- Generated by _mod_tools/package_editor_win.sh. A release build has the self test and the smoke
-- test disabled; see the RELEASE handling near the top of main.lua.
return { release = true }
LUA

# ---- 3. pack the archive (main.lua must sit at the archive root) -----------------------
( cd "$STAGE" && zip -9 -q -r ../editor.love . )
rm -rf "$STAGE"

# ---- 4. fuse: love.exe with the archive appended is a self-contained executable ---------
cat "$LW/love.exe" "$OUT/editor.love" > "$OUT/CePackEditor.exe"
cp "$LW/love.exe" "$OUT/love.exe"

# ---- 5. runtime libraries --------------------------------------------------------------
for d in love.dll lua51.dll mpg123.dll msvcp120.dll msvcr120.dll OpenAL32.dll SDL2.dll; do
  cp "$LW/$d" "$OUT/"
done
cp "$LW/license.txt" "$OUT/LICENSE-love.txt"
cp "$LW/readme.txt" "$OUT/README-love.txt"
cp "$DIST/使用说明.txt" "$OUT/使用说明.txt"

# ---- 6. zip ----------------------------------------------------------------------------
( cd "$DIST" && rm -f CellToSingularityEditor-win64.zip \
  && zip -9 -q -r CellToSingularityEditor-win64.zip Editor-win64 )

echo "release build: $OUT"
echo "  CePackEditor.exe  $(stat -c%s "$OUT/CePackEditor.exe") bytes"
echo "  editor.love       $(stat -c%s "$OUT/editor.love") bytes"
echo "  zip               $(stat -c%s "$DIST/CellToSingularityEditor-win64.zip") bytes"
